version: '3'
services:
  node:
    build:
      context: ./
      dockerfile: ./docker/node/Dockerfile
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "4000:4000"
    links:
      - mongodb
    restart: on-failure

  mongodb:
    image: mongo:4.2.6
    expose:
      - "27017"
    volumes:
      - ~/data/db:/data/db
    restart: on-failure